require_relative "seeds/users"
require_relative "seeds/profiles"
require_relative "seeds/tags"
require_relative "seeds/portfolios"
require_relative "seeds/skills"
require_relative "seeds/careers.rb"
require_relative "seeds/certifications.rb"
require_relative "seeds/hobbies.rb"
